function [info] = write_opentrades_php(info)

opentrades_array = transpose({info.web.home.json.ot_table(:).comp_name});

for i = 1:size(opentrades_array,1)
    try
%% Pull Symbol Data
        tradename = opentrades_array{i};
        tradesymbol = tradename(1:3); % may not be used

php_array = ['<!DOCTYPE html>\n' ...
              '<html>\n' ...
              '<head>\n' ...
              '<link rel=''stylesheet'' type=''text/css'' href=''/css/opentrades.css'' />\n' ...
              '<script src=''//code.jquery.com/jquery-1.11.0.min.js''></script>\n' ...
              '<script src=''//code.jquery.com/jquery-migrate-1.2.1.min.js''></script>\n' ...
              '<script src=''http://code.highcharts.com/stock/highstock.js''></script>\n' ...
              '<script src=''http://code.highcharts.com/stock/modules/exporting.js''></script>\n' ...
              '</head>\n' ...
              '<body>\n' ...
              '<div id=''home_link'' class=''link'' style=''text-align:center;line-height:50px''>\n' ...
              '<a class=''tradeopps_button'' href=''/tradeopps.php'' target=''_self''>TRADEOPPS</a>\n' ...
              '<a class=''homepage_button'' href=''/home.php'' target=''_self''>HOME</a>\n' ...
              '<a class=''interactivebrokers_button'' href=''https://www.interactivebrokers.com/ind/en/main.php'' target=''_blank''>IB</a>\n' ...
              '</div>\n' ...
              '<div id=''left_margin'' style=''float:left; width: 18%%;height:640px''>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<table class=''info_table'';>\n' ...
              '<caption>Weighted Trade Info</caption>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Trade Name</th>\n' ...
              '<td id=''trade_name''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>DTE</th>\n' ...
              '<td id=''dte''></td>\n' ...
              '</tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Breakeven</th>\n' ...
              '<td id=''breakeven''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Current UL</th>\n' ...
              '<td id=''current_ul''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Short Strike</th>\n' ...
              '<td id=''short_strike''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Long Strike</th>\n' ...
              '<td id=''long_strike''></td>\n' ...
              '</tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Premium Paid</th>\n' ...
              '<td id=''premium_paid''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Credit Received</th>\n' ...
              '<td id=''credit_recieved''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>NCR</th>\n' ...
              '<td id=''ncr''></td>\n' ...
              '</tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Max Profit</th>\n' ...
              '<td id=''max_profit''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Max Loss</th>\n' ...
              '<td id=''max_loss''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>PnL</th>\n' ...
              '<td id=''pl''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>POP</th>\n' ...
              '<td id=''pop''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''right_margin'' style=''float:right; width: 23%%;height:700px''>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Aroon</th>\n' ...
              '<td id=''aroon''></td>\n' ...
              '<th id=''data_header''>OSMA</th>\n' ...
              '<td id=''osma''></td>\n' ...
              '<th id=''data_header''>MACD</th>\n' ...
              '<td id=''macd''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Stoch %%K</th>\n' ...
              '<td id=''stoch_k''></td>\n' ...
              '<th id=''data_header''>Stoch %%D</th>\n' ...
              '<td id=''stoch_d''></td>\n' ...
              '<th id=''data_header''>Stoch Hist</th>\n' ...
              '<td id=''stoch_histogram''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Percent B</th>\n' ...
              '<td id=''pctb''></td>\n' ...
              '<th id=''data_header''>Bandwidth</th>\n' ...
              '<td id=''bandwidth''></td>\n' ...
              '<th id=''data_header''>Avg Band</th>\n' ...
              '<td id=''avg_bandwidth''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Current Volume</th>\n' ...
              '<td id=''current_volume''></td>\n' ...
              '<th id=''data_header''>Volume Ultra</th>\n' ...
              '<td id=''volume_ultra''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV</th>\n' ...
              '<td id=''current_iv''></td>\n' ...
              '<th id=''data_header''>HV</th>\n' ...
              '<td id=''current_hv''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Vol Osc</th>\n' ...
              '<td id=''vol_oscillator''></td>\n' ...
              '<th id=''data_header''>Avg Osc</th>\n' ...
              '<td id=''avg_vol_oscillator''></td>\n' ...
              '<th id=''data_header''>Vol Ultra</th>\n' ...
              '<td id=''vol_ultra''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV Rank</th>\n' ...
              '<td id=''iv_rank''></td>\n' ...
              '<th id=''data_header''>IV Percentile</th>\n' ...
              '<td id=''iv_percentile''></td>\n' ...
              '<th id=''data_header''>IV PctV</th>\n' ...
              '<td id=''iv_pctv''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''padding'' style=''float:left;height: 20px;width:59%%;''></div>\n' ...
              '<div id=''chart_stock'' style=''float:left;height: 360px;width:59%%;''></div>\n' ...
              '<div id=''chart_iv'' style=''float:left;height: 300px;width:59%%;''></div>\n' ...
              '<div id=''padding'' style=''float:left;height: 80px;width:16%%;''></div>\n' ...
              '<div id=''open_trades'' style=''float:left; width: 1050px;height:260px;overflow:auto;overflow-x:hidden''>\n' ...
              '<table class=''open_trades_table'' id=''open_trades_table''>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<script src=''/js/' tradename '.js''></script>\n' ...
              '</body>\n' ...
              '</html>']; % end 
        
                 
filename = ['F:/inetpub/ammoroot/opentrades/' tradename '.php'];
fid = fopen(filename,'w'); 
fprintf(fid,php_array);
fclose(fid);               
info.web.opentrades.php.(tradename) = php_array;
 

    catch ME
    end
end
end
