function [info] = write_opentrades_js(info)

opentrades_array = transpose({info.web.home.json.ot_table(:).comp_name});

for i = 1:size(opentrades_array,1)
    try
%% Pull Symbol Data
        tradename = opentrades_array{i};
        tradesymbol = tradename(1:3);


js_array = ['$(document).ready(function() {\n' ...
                     '$.ajax({\n' ...
                     'url:''/json/' tradename '.json'',\n' ...
                     'type:''GET'',\n' ...
                     'contentType: ''application/json; charset=utf-8'',\n' ...
                     'success: function(data) {\n' ...
                     'console.log(data);\n' ...
                     'populate_home(data);\n' ...
                     'populate_open_trades(data);\n' ...
                     '},\n' ...
                     'error: (function(){\n' ...
                     'alert(''Error retrieving info'');\n' ...
                     '})\n' ...
                     '});\n' ...
                     'function populate_home(values) {\n' ...
                     '$(''#trade_name'').text(values[0]);\n' ...
                     '$(''#dte'').text(values[1]);\n' ...
                     '$(''#current_ul'').text(values[2]);\n' ...
                     '$(''#long_strike'').text(values[3]);\n' ...
                     '$(''#premium_paid'').text(values[4]);\n' ...
                     '$(''#short_strike'').text(values[5]);\n' ...
                     '$(''#credit_recieved'').text(values[6]);\n' ...
                     '$(''#ncr'').text(values[7]);\n' ...
                     '$(''#breakeven'').text(values[8]);\n' ...
                     '$(''#max_profit'').text(values[9]);\n' ...
                     '$(''#max_loss'').text(values[10]);\n' ...
                     '$(''#pl'').text(values[11]);\n' ...
                     '$(''#pop'').text(values[12]);\n' ...
                     '$(''#aroon'').text(values[30]);\n' ...
                     '$(''#stoch_k'').text(values[31]);\n' ...
                     '$(''#stoch_d'').text(values[32]);\n' ...
                     '$(''#osma'').text(values[33]);\n' ...
                     '$(''#pctb'').text(values[34]);\n' ...
                     '$(''#bandwidth'').text(values[35]);\n' ...
                     '$(''#current_iv'').text(values[36]);\n' ...
                     '$(''#current_hv'').text(values[37]);\n' ...
                     '$(''#iv_rank'').text(values[38]);\n' ...
                     '$(''#iv_percentile'').text(values[39]);\n' ...
                     '$(''#stoch_histogram'').text(values[46]);\n' ...
                     '$(''#vol_oscillator'').text(values[47]);\n' ...
                     '$(''#avg_bandwidth'').text(values[48]);\n' ...
                     '$(''#macd'').text(values[49]);\n' ...
                     '$(''#avg_vol_oscillator'').text(values[50]);\n' ...
                     '$(''#vol_ultra'').text(values[51]);\n' ...
                     '$(''#iv_pctv'').text(values[52]);\n' ...
                     '$(''#current_volume'').text(values[65]);\n' ...
                     '$(''#volume_ultra'').text(values[66]);\n' ...
                     '}\n' ...
                     'function populate_open_trades(values) {\n' ...
                     'open_trade_list = '''';\n' ... 
                     'open_trade_list += ''<thead><tr><th>LocalSymbol</th><th>Right</th><th>Position</th><th>Expiry</th><th>Strike</th><th>MV</th><th>Cost/Credit</th><th>IV</th><th>Delta</th><th>POS</th><th>Gamma</th><th>Theta</th><th>Vega</th><th>PL</th><th>PoMax</th></tr></thead>'';\n' ... 
                     'if (values[13][1][1] != null)\n' ...
                     '{for (var i = 0; i < values[13].length; i++) \n' ...
                     '{open_trade_list += ''<tbody><tr><td>''+ values[14][i] +''</td><td>''+ values[15][i] +''</td><td>''+ values[16][i] +''</td><td>''+ values[17][i]+''</td><td>''+ values[18][i] +''</td><td>''+ values[19][i] +''</td><td>''+ values[20][i] +''</td><td>''+ values[41][i] +''</td><td>''+ values[42][i] +''</td><td>''+ values[53][i] +''</td><td>''+ values[43][i] +''</td><td>''+ values[44][i] +''</td><td>''+ values[45][i] +''</td><td>''+ values[22][i] +''</td><td>''+ values[23][i] +''</td></tr></tbody>'';} \n' ...
                     '}\n' ...
                     'else \n' ...
                     '{open_trade_list += ''<tbody><tr><td>''+ values[14] +''</td><td>''+ values[15] +''</td><td>''+ values[16] +''</td><td>''+ values[17]+''</td><td>''+ values[18] +''</td><td>''+ values[19] +''</td><td>''+ values[20] +''</td><td>''+ values[41] +''</td><td>''+ values[42] +''</td><td>''+ values[53][i] +''</td><td>''+ values[43] +''</td><td>''+ values[44] +''</td><td>''+ values[45] +''</td><td>''+ values[22] +''</td><td>''+ values[23] +''</td></tr></tbody>'';\n' ...
                     '} \n' ...
                     '$(''#open_trades_table'').html(open_trade_list);\n' ...
                     'stock = new Array()\n' ...
                     'highband = new Array()\n' ...
                     'middleband = new Array()\n' ...
                     'lowband = new Array()\n' ...
                     'open = new Array()\n' ...
                     'high = new Array()\n' ...
                     'low = new Array()\n' ...
                     'close = new Array()\n' ...
                     'volume = new Array()\n' ...
                     'date = new Array()\n' ...
                     'avg_volume = new Array()\n' ...
                     'var ohlc = [];\n' ...
                     'var volm = [];\n' ...
                     'var hb = [];\n' ...
                     'var mb = [];\n' ...
                     'var lb = [];\n' ...
                     'var avg_volm = [];\n' ...
                     'var groupingUnits = [[''day'',[1]]];\n' ...
                     'for (var i = 0; i < values[54].length; i ++ ) {date[i] = [parseInt(values[63][i])],volume[i] = [values[58][i][0]],open[i] = [values[54][i][0]],high[i] = [values[55][i][0]],low[i] = [values[56][i][0]],close[i] = [values[57][i][0]],highband[i] = [values[27][i][0]],middleband[i] = [values[28][i][0]],lowband[i] = [values[29][i][0]],avg_volume[i] = [values[67][i][0]]}\n' ...
                     'for (var i = 0; i < values[54].length; i ++ ) {ohlc.push([date[i][0],open[i][0],high[i][0],low[i][0],close[i][0]]);volm.push([date[i][0],volume[i][0]]);hb.push([date[i][0],highband[i][0]]);mb.push([date[i][0],middleband[i][0]]);lb.push([date[i][0],lowband[i][0]]);avg_volm.push([date[i][0],avg_volume[i][0]])}\n' ...
                     '$(''#chart_stock'').highcharts(''StockChart'',{\n' ...
                     'rangeSelector: {selected: 2},\n' ...
                     'credits: {enabled: false},\n' ...
                     'title: {text: ''' tradesymbol ' Price''},\n' ...
                     'yAxis: [{labels:{align: ''left'',x: 3},title: {text: ''''},height: ''85%%'',lineWidth: 0,tickInterval: 2},\n' ...
                     '{labels: {align: ''left'',x: 3},title: {text: ''''},top: ''85%%'',height: ''15%%'',offset: 0,lineWidth: 0}\n' ...
                     '],\n' ...
                     'series: [{type: ''candlestick'',\n' ...
                     'name: ''ohlc'',\n' ...
                     'data: ohlc,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''highband'',\n' ...
                     'data: hb,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''ShortDash'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''middleband'',\n' ...
                     'data: mb,\n' ...
                     'color: ''#C6C6A9'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''ShortDash'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''lowband'',\n' ...
                     'data: lb,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''ShortDash'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''column'',\n' ...
                     'name: ''volume'',\n' ...
                     'data: volm,\n' ...
                     'yAxis: 1,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'yAxis: 1,\n' ...
                     'name: ''avg volume'',\n' ...
                     'data: avg_volm,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''ShortDash'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '}],\n' ...
                     '}),\n' ...
                     'hv = new Array()\n' ...
                     'iv = new Array()\n' ...
                     'iv_open = new Array()\n' ...
                     'iv_high = new Array()\n' ...
                     'iv_low = new Array()\n' ...
                     'iv_close = new Array()\n' ...
                     'iv_date = new Array()\n' ...
                     'var iv_ohlc = [];\n' ...
                     'var hv = [];\n' ...
                     'var groupingUnits = groupingUnits = [[''day'',[1]]]\n' ...
                     'for (var i = 0; i < values[59].length; i ++ ) {date[i] = [parseInt(values[64][i])],hv[i] = [values[25][i][0]],iv_open[i] = [values[59][i][0]],iv_high[i] = [values[60][i][0]],iv_low[i] = [values[61][i][0]],iv_close[i] = [values[62][i][0]]}\n' ...
                     'for (var i = 0; i < values[59].length; i ++ ) {iv_ohlc.push([date[i][0],iv_open[i][0],iv_high[i][0],iv_low[i][0],iv_close[i][0]]);hv.push([date[i][0],hv[i][0]]);}\n' ...
                     '$(''#chart_iv'').highcharts(''StockChart'',{\n' ...
                     'rangeSelector: {selected: 2},\n' ...
                     'credits: {enabled: false},\n' ...
                     'title: {text: ''' tradesymbol ' Volatility''},\n' ...
                     'yAxis: [{labels:{ align: ''left'',x: 3},title: {text: ''''},height: ''100%%'',lineWidth: 0,tickInterval: .02}],\n' ...
                     'series: [{type: ''candlestick'',\n' ...
                     'name: ''iv'',\n' ...
                     'data: iv_ohlc,\n' ...
                     'dataGrouping: {units: groupingUnits},\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''hv'',\n' ...
                     'data: hv,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '}]\n' ...
                     '});\n' ...
                     '}\n' ...
                     '});\n']; % end 
        
                 
filename = ['F:/inetpub/ammoroot/js/' tradename '.js'];
fid = fopen(filename,'w'); 
fprintf(fid,js_array);
fclose(fid);               
info.web.opentrades.js.(tradename) = js_array;
 

    catch ME
    end
end
end
%                      '$(''#impliedvol'').text(values[40]);\n' ...
%                      '$(''#impliedvol'').text(values[41]);\n' ...
%                      '$(''#delta'').text(values[42]);\n' ...
%                      '$(''#gamma'').text(values[43]);\n' ...
%                      '$(''#theta'').text(values[44]);\n' ...
%                      '$(''#vega'').text(values[45]);\n' ...

% Change line belows
% <th>Price</th><th>IV</th><th>Delta</th><th>Gamma</th><th>Theta</th><th>Vega</th>
 % <td>''+ values[40][i] +''</td><td>''+ values[41][i] +''</td><td>''+ values[42][i] +''</td><td>''+ values[43][i] +''</td><td>''+ values[44][i] +''</td><td>''+ values[45][i] +''</td>