function [info] = write_tradeopps_php(info)


for i = 1:size(info.ammo.stage,2)
    try

stage = info.ammo.stage(i);
symbol = stage.symbol;

php_array = ['<!DOCTYPE html>\n' ...
              '<html>\n' ...
              '<head>\n' ...
              '<link rel=''stylesheet'' type=''text/css'' href=''/css/tradeopps.css'' />\n' ...
              '<script src=''//code.jquery.com/jquery-1.11.0.min.js''></script>\n' ...
              '<script src=''//code.jquery.com/jquery-migrate-1.2.1.min.js''></script>\n' ...
              '<script src=''http://code.highcharts.com/stock/highstock.js''></script>\n' ...
              '<script src=''http://code.highcharts.com/stock/highcharts-more.js''></script>\n' ...
              '<script src=''http://code.highcharts.com/stock/modules/exporting.js''></script>\n' ...
              '</head>\n' ...
              '<body>\n' ...
              '<div id=''home_link'' class=''link'' style=''text-align:center;line-height:50px''>\n' ...
              '<a class=''tradeopps_button'' href=''/tradeopps.php'' target=''_self''>TRADEOPPS</a>\n' ...
              '<a class=''homepage_button'' href=''/home.php'' target=''_self''>HOME</a>\n' ...
              '<a class=''interactivebrokers_button'' href=''https://www.interactivebrokers.com/ind/en/main.php'' target=''_blank''>IB</a>\n' ...
              '</div>\n' ...
              '<div id=''left_margin'' style=''float:left; width: 5%%;height:800px''></div>\n' ...
              '<div id=''right_margin'' style=''float:right; width: 5%%;height:800px''></div>\n' ...
              '<div id=''padding'' style=''float:left;height: 20px;width:70%%;''></div>\n' ...
              '<div id=''chart_stock'' style=''float:left;height: 400px;width:89%%;''></div>\n' ...
              '<div id=''indicator_div'' style=''float:left;height: 100%%;width:25%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>UL</th>\n' ...
              '<td id=''ul_price''></td>\n' ...
              '<th id=''data_header''>Resistance</th>\n' ...
              '<td id=''resistance''></td>\n' ...
              '<th id=''data_header''>Support</th>\n' ...
              '<td id=''support''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>3 MA</th>\n' ...
              '<td id=''ma_iii''></td>\n' ...
              '<th id=''data_header''>100 MA</th>\n' ...
              '<td id=''ma_c''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Volume</th>\n' ...
              '<td id=''current_volume''></td>\n' ...
              '<th id=''data_header''>Volume Ultra</th>\n' ...
              '<td id=''volume_ultra''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''indicator_div'' style=''float:left;height: 100%%;width:34%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Pct B</th>\n' ...
              '<td id=''bb_pctb''></td>\n' ...
              '<th id=''data_header''>Bandwidth</th>\n' ...
              '<td id=''bb_bandwidth''></td>\n' ...
              '<th id=''data_header''>Avg Band</th>\n' ...
              '<td id=''bb_avg_bandwidth''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>OSMA</th>\n' ...
              '<td id=''osma''></td>\n' ...
              '<th id=''data_header''>MACD</th>\n' ...
              '<td id=''macd''></td>\n' ...
              '<th id=''data_header''>Avg MACD</th>\n' ...
              '<td id=''avg_macd''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>%%K</th>\n' ...
              '<td id=''stoch_pctk''></td>\n' ...
              '<th id=''data_header''>%%D</th>\n' ...
              '<td id=''stoch_pctd''></td>\n' ...
              '<th id=''data_header''>Stoch Hist</th>\n' ...
              '<td id=''stoch_histogram''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''indicator_div'' style=''float:left;height: 100%%;width:25%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>ATR</th>\n' ...
              '<td id=''atr''></td>\n' ...
              '<th id=''data_header''>Avg ATR</th>\n' ...
              '<td id=''avg_atr''></td>\n' ...
              '<th id=''data_header''>TR</th>\n' ...
              '<td id=''tr''></td>\n' ...
              '</tr>\n' ...        
              '<tr>\n' ...
              '<th id=''data_header''>Aroon</th>\n' ...
              '<td id=''aroon''></td>\n' ...
              '<th id=''data_header''>Avg Aroon</th>\n' ...
              '<td id=''aroon_avg_oscillator''></td>\n' ...
              '<th id=''data_header''>Trend</th>\n' ...
              '<td id=''aroon_trend''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '<tr><td><br/></td></tr>\n' ...
              '</div>\n' ...
              '<div id=''chart_iv'' style=''float:left;height: 360px;width:89%%;''></div>\n' ...
              '<div id=''padding'' style=''float:left;height: 10px;width:10%%;''></div>\n' ...
              '<div id=''vol_div'' style=''float:left;height: 40px;width:29%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Current IV</th>\n' ...
              '<td id=''current_iv''></td>\n' ...
              '<th id=''data_header''>Current HV</th>\n' ...
              '<td id=''current_hv''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>Vol Osc</th>\n' ...
              '<td id=''vol_oscillator''></td>\n' ...
              '<th id=''data_header''>Avg Osc</th>\n' ...
              '<td id=''avg_vol_oscillator''></td>\n' ...
              '<th id=''data_header''>Vol Ultra</th>\n' ...
              '<td id=''vol_ultra''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''vol_div'' style=''float:left;height: 40px;width:29%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV Rank</th>\n' ...
              '<td id=''iv_rank''></td>\n' ...
              '<th id=''data_header''>HV Rank</th>\n' ...
              '<td id=''hv_rank''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV Percentile</th>\n' ...
              '<td id=''iv_percentile''></td>\n' ...
              '<th id=''data_header''>HV Percentile</th>\n' ...
              '<td id=''hv_percentile''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<div id=''vol_div'' style=''float:left;height: 40px;width:29%%;''>\n' ...
              '<table class=''stock_table''>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV PctV</th>\n' ...
              '<td id=''iv_pctv''></td>\n' ...
              '<th id=''data_header''>HV PctV</th>\n' ...
              '<td id=''hv_pctv''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV Max</th>\n' ...
              '<td id=''iv_max''></td>\n' ...
              '<th id=''data_header''>HV Max</th>\n' ...
              '<td id=''hv_max''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '<tr>\n' ...
              '<th id=''data_header''>IV Min</th>\n' ...
              '<td id=''iv_min''></td>\n' ...
              '<th id=''data_header''>HV Min</th>\n' ...
              '<td id=''hv_min''></td>\n' ...
              '<th id=''fill''></th>\n' ...
              '<td id=''fill''></td>\n' ...
              '</tr>\n' ...
              '</table>\n' ...
              '</div>\n' ...
              '<script src=''/js/' symbol '.js''></script>\n' ...
              '</body>\n' ...
              '</html>']; % end 
        
                 
filename = ['F:/inetpub/ammoroot/tradeopps/' symbol '.php'];
fid = fopen(filename,'w'); 
fprintf(fid,php_array);
fclose(fid);               
info.web.tradeopps.php.(symbol) = php_array;
 
    catch ME
    end
end
end
