function [info] = write_tradeopps_js(info)

for i = 1:size(info.ammo.stage,2)
    try

stage = info.ammo.stage(i);
symbol = stage.symbol;
    
    
js_array = ['$(document).ready(function() {\n' ...
                     '$.ajax({\n' ...
                     'url:''/json/' symbol '.json'',\n' ...
                     'type:''GET'',\n' ...
                     'contentType: ''application/json; charset=utf-8'',\n' ...
                     'success: function(data) {\n' ...
                     'console.log(data);\n' ...
                     'populate_indicators(data);\n' ...
                     'populate_charts(data);\n' ...
                     '},\n' ...
                     'error: (function(){\n' ...
                     'alert(''Error retrieving info'');\n' ...
                     '})\n' ...
                     '});\n' ...
                     'function populate_indicators(values) {\n' ...
                     '$(''#ul_price'').text(values[6]);\n' ...
                     '$(''#ma_iii'').text(values[7]);\n' ...
                     '$(''#ma_c'').text(values[8]);\n' ...
                     '$(''#bb_pctb'').text(values[9]);\n' ...
                     '$(''#bb_bandwidth'').text(values[10]);\n' ...
                     '$(''#bb_avg_bandwidth'').text(values[11]);\n' ...
                     '$(''#osma'').text(values[12]);\n' ...
                     '$(''#macd'').text(values[13]);\n' ...
                     '$(''#osmacross'').text(values[14]);\n' ...
                     '$(''#macdcentercross'').text(values[15]);\n' ...
                     '$(''#stoch_pctk'').text(values[16]);\n' ...
                     '$(''#stoch_pctd'').text(values[17]);\n' ...
                     '$(''#stoch_histogram'').text(values[18]);\n' ...
                     '$(''#atr'').text(values[19]);\n' ...
                     '$(''#tr'').text(values[20]);\n' ...
                     '$(''#aroon'').text(values[21]);\n' ...
                     '$(''#aroon_avg_oscillator'').text(values[22]);\n' ...
                     '$(''#aroon_trend'').text(values[23]);\n' ...
                     '$(''#aroon_signalcross'').text(values[24]);\n' ...
                     '$(''#resistance'').text(values[25]);\n' ...
                     '$(''#support'').text(values[26]);\n' ...
                     '$(''#vol_oscillator'').text(values[27]);\n' ...
                     '$(''#avg_vol_oscillator'').text(values[28]);\n' ...
                     '$(''#current_hv'').text(values[29]);\n' ...
                     '$(''#hv_rank'').text(values[30]);\n' ...
                     '$(''#hv_percentile'').text(values[31]);\n' ...
                     '$(''#hv_min'').text(values[32]);\n' ...
                     '$(''#hv_max'').text(values[33]);\n' ...
                     '$(''#hv_pctv'').text(values[34]);\n' ...
                     '$(''#current_iv'').text(values[35]);\n' ...
                     '$(''#iv_rank'').text(values[36]);\n' ...
                     '$(''#iv_percentile'').text(values[37]);\n' ...
                     '$(''#iv_min'').text(values[38]);\n' ...
                     '$(''#iv_max'').text(values[39]);\n' ...
                     '$(''#iv_pctv'').text(values[40]);\n' ...
                     '$(''#avg_atr'').text(values[41]);\n' ...
                     '$(''#avg_macd'').text(values[42]);\n' ...
                     '$(''#vol_ultra'').text(values[43]);\n' ...
                     '$(''#current_volume'').text(values[55]);\n' ...
                     '$(''#volume_ultra'').text(values[56]);\n' ...
                     '}\n' ...
                     'function populate_charts(values) {\n' ...
                     'stock = new Array()\n' ...
                     'highband = new Array()\n' ...
                     'middleband = new Array()\n' ...
                     'lowband = new Array()\n' ...
                     'open = new Array()\n' ...
                     'high = new Array()\n' ...
                     'low = new Array()\n' ...
                     'close = new Array()\n' ...
                     'volume = new Array()\n' ...
                     'date = new Array()\n' ...
                     'avg_volume = new Array()\n' ...
                     'call_iv_strike = new Array()\n' ...
                     'put_iv_strike = new Array()\n' ...
                     'call_hv_strike = new Array()\n' ...
                     'put_hv_strike = new Array()\n' ...
                     'var ohlc = [];\n' ...
                     'var volm = [];\n' ...
                     'var hb = [];\n' ...
                     'var mb = [];\n' ...
                     'var lb = [];\n' ...
                     'var avg_volm = [];\n' ...
                     'var bollinger_area = [];\n' ...
                     'var iv_area = [];\n' ...
                     'var hv_area = [];\n' ...
                     'var groupingUnits = [[''day'',[1]]];\n' ...
                     'for (var i = 0; i < values[44].length; i ++ ) {date[i] = [parseInt(values[53][i])],volume[i] = [values[48][i][0]],open[i] = [values[44][i][0]],high[i] = [values[45][i][0]],low[i] = [values[46][i][0]],close[i] = [values[47][i][0]],highband[i] = [values[3][i][0]],middleband[i] = [values[4][i][0]],lowband[i] = [values[5][i][0]],avg_volume[i] = [values[57][i][0]]}\n' ...
                     'for (var i = 0; i < values[44].length; i ++ ) {ohlc.push([date[i][0],open[i][0],high[i][0],low[i][0],close[i][0]]);volm.push([date[i][0],volume[i][0]]);hb.push([date[i][0],highband[i][0]]);mb.push([date[i][0],middleband[i][0]]);lb.push([date[i][0],lowband[i][0]]);avg_volm.push([date[i][0],avg_volume[i][0]]),bollinger_area.push([date[i][0],highband[i][0],lowband[i][0]])}\n' ...
                     'for (var i = 0; i < values[58].length; i ++ ) {call_iv_strike[i] = [values[58][i][0]]}\n' ...
                     'for (var i = 0; i < values[59].length; i ++ ) {put_iv_strike[i] = [values[59][i][0]]}\n' ...
                     'for (var i = 0; i < values[60].length; i ++ ) {call_hv_strike[i] = [values[60][i][0]]}\n' ...
                     'for (var i = 0; i < values[61].length; i ++ ) {put_hv_strike[i] = [values[61][i][0]]}\n' ...
                     'for (var i = 0; i < values[58].length; i ++ ) {iv_area.push([date[i][0],call_iv_strike[i][0],put_iv_strike[i][0]])}\n' ...
                     'for (var i = 0; i < values[60].length; i ++ ) {hv_area.push([date[i][0],call_hv_strike[i][0],put_hv_strike[i][0]])}\n' ...
                     '$(''#chart_stock'').highcharts(''StockChart'',{\n' ...
                     'rangeSelector: {selected: 2},\n' ...
                     'credits: {enabled: false},\n' ...
                     'title: {text: ''' symbol ' Price''},\n' ...
                     'yAxis: [{labels:{align: ''left'',x: 3},title: {text: ''''},height: ''85%%'',lineWidth: 2,tickInterval: 2},\n' ...
                     '{labels: {align: ''left'',x: 3},title: {text: ''''},top: ''85%%'',height: ''15%%'',offset: 0,lineWidth: 2}\n' ...
                     '],\n' ...
                     'series: [\n' ...
                     '{type: ''arearange'',\n' ...
                     'name: ''iv_area'',\n' ...
                     'data: iv_area,\n' ...
                     'lineWidth: 2,\n' ...
                     'color: ''#48ABBC''\n' ...
                     '},\n' ...
                     '{type: ''arearange'',\n' ...
                     'name: ''hv_area'',\n' ...
                     'data: hv_area,\n' ...
                     'lineWidth: 2,\n' ...
                     'color: ''#000000''\n' ...
                     '},\n' ...
                     '{type: ''arearange'',\n' ...
                     'name: ''bollinger_area'',\n' ...
                     'data: bollinger_area,\n' ...
                     'lineWidth: 2,\n' ...
                     'color: ''#FFFFFF''\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''highband'',\n' ...
                     'data: hb,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''solid'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''middleband'',\n' ...
                     'data: mb,\n' ...
                     'color: ''#424242'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''solid'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''lowband'',\n' ...
                     'data: lb,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''solid'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''candlestick'',\n' ...
                     'name: ''ohlc'',\n' ...
                     'data: ohlc,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''column'',\n' ...
                     'name: ''volume'',\n' ...
                     'data: volm,\n' ...
                     'yAxis: 1,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'yAxis: 1,\n' ...
                     'name: ''avg volume'',\n' ...
                     'data: avg_volm,\n' ...
                     'color: ''#2C576F'',\n' ...
                     'lindeWidth: 1,\n' ...
                     'dashStyle: ''ShortDash'',\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '}],\n' ...
                     '}),\n' ...
                     'hv = new Array()\n' ...
                     'iv = new Array()\n' ...
                     'iv_open = new Array()\n' ...
                     'iv_high = new Array()\n' ...
                     'iv_low = new Array()\n' ...
                     'iv_close = new Array()\n' ...
                     'iv_date = new Array()\n' ...
                     'var iv_ohlc = [];\n' ...
                     'var hv = [];\n' ...
                     'var groupingUnits = groupingUnits = [[''day'',[1]]]\n' ...
                     'for (var i = 0; i < values[0].length; i ++ ) {date[i] = [parseInt(values[54][i])],hv[i] = [values[1][i][0]],iv_open[i] = [values[49][i][0]],iv_high[i] = [values[50][i][0]],iv_low[i] = [values[51][i][0]],iv_close[i] = [values[52][i][0]]}\n' ...
                     'for (var i = 0; i < values[0].length; i ++ ) {iv_ohlc.push([date[i][0],iv_open[i][0],iv_high[i][0],iv_low[i][0],iv_close[i][0]]);hv.push([date[i][0],hv[i][0]]);}\n' ...
                     '$(''#chart_iv'').highcharts(''StockChart'',{\n' ...
                     'rangeSelector: {selected: 2},\n' ...
                     'credits: {enabled: false},\n' ...
                     'title: {text: ''' symbol ' Volatility''},\n' ...
                     'yAxis: [{labels:{ align: ''left'',x: 3},title: {text: ''''},height: ''100%%'',lineWidth: 2,tickInterval: .02}],\n' ...
                     'series: [{type: ''candlestick'',\n' ...
                     'name: ''iv'',\n' ...
                     'data: iv_ohlc,\n' ...
                     'dataGrouping: {units: groupingUnits},\n' ...
                     '},\n' ...
                     '{type: ''line'',\n' ...
                     'name: ''hv'',\n' ...
                     'data: hv,\n' ...
                     'dataGrouping: {units: groupingUnits}\n' ...
                     '}]\n' ...
                     '});\n' ...
                     '}\n' ...
                     '});\n']; % end 
        
                 
filename = ['F:/inetpub/ammoroot/js/' symbol '.js'];
fid = fopen(filename,'w'); 
fprintf(fid,js_array);
fclose(fid);               
info.web.tradeopps.js.(symbol) = js_array;
 

    catch ME
    end
end
end